name: CI

on:
  push:
    branches:
    - release
  pull_request:
    branches:
    - release
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=1.0.7" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --output ../../src/DocMaker.sln
    - name: Push
      run: dotnet nuget push NuGet.Workflow.${VERSION}.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${NUGET_API_KEY}
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
