name: CI

on:
  push:
    branches:
    - release
  pull_request:
    branches:
    - release
  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/release
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/release
    - name: Set VERSION variable from tag
      run: echo "VERSION=2.0.0" >> $GITHUB_ENV
    - name: Build
      run: dotnet build ./src/DocMaker.sln --configuration Release /p:Version=${VERSION}
    - name: Pack
      run: dotnet pack ./src/DocMaker.sln --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push DocMaker.${VERSION}.nupkg -k ${GITHUB_TOKEN} -s https://api.nuget.org/v3/index.json
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
